# Generated by Django 4.1.5 on 2023-01-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_options_alter_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='categoty',
            new_name='category',
        ),
    ]
